#!/usr/bin/env bash
set -euo pipefail

SSHRC_ROOT=$(dirname "$BASH_SOURCE")
SSHRC_HOME=${SSHRC_HOME:=~/.config/sshrc}

SSHRC_BOOT=$SSHRC_ROOT/boot.sh
. "$SSHRC_BOOT"

client() {
  destination=$1
  shift
  bootstrap="exec bash --norc -c $(sh_escape "$(bootstrap "$@")")"
  options=()
  if (($# == 0)); then
    options+=(-t)
  fi
  ssh "${options[@]}" "$destination" "$bootstrap"
}

sh_escape() {
  echo "'${1//"'"/"'\\''"}'"
}

bootstrap() {
  cat "$SSHRC_BOOT"
  echo 'init'
  send "$SSHRC_ROOT" '"$SSHRC_ROOT"'
  if [[ -d "$SSHRC_HOME" ]]; then
    send "$SSHRC_HOME" '"$SSHRC_HOME"'
  fi
  echo 'exec "$SSHRC_ROOT/core" server' ${@+$(printf ' %q' "$@")}
}

send() {
  local from=$1 to=$2
  echo "unpack $to << __"
  pack "$from"
  echo '__'
}

pack() {
  tar cz -h -C "$1" . | _base64
}

server() {
  signal_handlers
  export SSHRC_SESSION_TYPE=shell
  if (($# > 0)); then
    SSHRC_SESSION_TYPE=command
  fi
  "$SSHRC_ROOT/shell" ${*+-c "$*"}
}

boot
mode=$1
shift

case $mode in
  client|server) $mode "$@" ;;
  *) fatal "Unknown mode '$mode'" ;;
esac
