#!/usr/bin/env bash
set -euo pipefail

SSHRC_ROOT=$(dirname "$BASH_SOURCE")
SSHRC_HOME=${SSHRC_HOME:=~/.sshrc}

fatal() {
  echo >&2 "$*"
  exit 1
}

client() {
  destination=$1
  shift
  bootstrap="exec bash --norc --noprofile -c $(sh_escape "$(bootstrap "$@")")"
  options=()
  if (($# == 0)); then
    options+=(-t)
  fi
  ssh "${options[@]}" "$destination" "$bootstrap"
}

sh_escape() {
  echo "'${1//"'"/"'\\''"}'"
}

bootstrap() {
  declare -f init unpack
  echo 'init'
  send "$SSHRC_ROOT" '"$SSHRC_ROOT"'
  if [[ -d "$SSHRC_HOME" ]]; then
    send "$SSHRC_HOME" '"$SSHRC_HOME"'
  fi
  echo -n 'exec "$SSHRC_ROOT/sshrc-core" server'
  if (($# > 0)); then
    printf ' %q' "$@"
  fi
  echo
}

init() {
  export SSHRC_ROOT=$(mktemp -d -t sshrc.XXXXXXXX)
  trap 'rm -rf "$SSHRC_ROOT"' EXIT

  export SSHRC_HOME=$SSHRC_ROOT/home
  mkdir "$SSHRC_HOME"
}

send() {
  local from=$1 to=$2
  echo "unpack $to << __"
  pack "$from"
  echo '__'
}

unpack() {
  openssl base64 -d | tar xz -C "$1"
}

pack() {
  tar cz -h -C "$1" . | openssl base64
}

server() {
  trap 'rm -rf "$SSHRC_ROOT"' EXIT
  if (($# == 0)); then
    bash -l
  else
    (eval "$*")
  fi
}

mode=$1
shift

case $mode in
  client|server) $mode "$@" ;;
  *) fatal "Unknown mode '$mode'" ;;
esac
